site_name: Infrastructure Documentation
repo_url: https://github.com/joejcollins/admiral-frendor
theme:
  name: readthedocs

nav:
  - Home: index.md

plugins:
  - search
  - mermaid2:
      javascript: https://unpkg.com/mermaid/dist/mermaid.min.js
      arguments:
        startOnLoad: true
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
