---
- name: Create a Google Cloud Storage Bucket
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a bucket
      google.cloud.gcp_storage_bucket:
        name: ansible-storage-module
        project: asgard
        auth_kind: serviceaccount
        service_account_file: "/tmp/key.json"
        state: present
      register: bucket_result

    - name: Debug bucket creation result
      debug:
        var: bucket_result
        