---
name: Pull Request Labeler

on:
  - pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Label PR
        uses: actions/labeler@v6
        with:
          configuration-path: .github/labeller.yml
