---
name: Run the Python Tests

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/run-all-tests.yml
      - src/**
      - tests/**

jobs:
  run_python_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/joejcollins/admiral-frendor:latest

    steps:
      - name: Checkout the repo.
        uses: actions/checkout@v5
        with:
          submodules: false
          clean: true

      - name: Run tests.
        run: |
          make venv
          make report
          make test
          make lint
